# Generated by Django 6.0.6 on 2026-06-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Jina la Dawa')),
                ('category', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('painkiller', 'Painkiller'), ('vitamin', 'Vitamin'), ('syrup', 'Syrup'), ('tablet', 'Tablet'), ('injection', 'Injection'), ('other', 'Nyingine')], max_length=50, verbose_name='Aina')),
                ('quantity', models.IntegerField(verbose_name='Idadi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bei (TZS)')),
                ('manufacture_date', models.DateField(verbose_name='Tarehe ya Kuzalishwa')),
                ('expiry_date', models.DateField(verbose_name='Tarehe ya Kuisha')),
                ('supplier', models.CharField(max_length=200, verbose_name='Msambazaji')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dawa',
                'verbose_name_plural': 'Dawa',
                'ordering': ['expiry_date'],
            },
        ),
    ]
